---
# vars/main.yml
# qbittorrent_enabled: please check global variables, because of allowedUnsafeSysctls
# Override these variables as needed
# your LAN network, watch out for conflicts with the VPN own DNS IP
qbittorrent_vpn_enabled: true
qbittorrent_vpn_provider: "proton"
qbittorrent_vpn_lan_network: "192.168.1.0/24"
qbittorrent_extra_env: []

# Advanced features
qbittorrent_privoxy_enabled: false
qbittorrent_unbound_enabled: false

# Ingress
qbittorrent_ingress_enabled: true

# Storage configuration overrides default storage classes
qbittorrent_config_persistence_enabled: true
qbittorrent_data_persistence_enabled: true
# qbittorrent_config_existing_claim: ""
# qbittorrent_data_existing_claim: ""

# Data for the wg0.conf, when using proton
qbittorrent_wg_copy_config: true
qbittorrent_wg_private_key: "changeme"
qbittorrent_wg_client_ip: "changeme"
qbittorrent_wg_dns_servers: "1.1.1.1"  # changeme
qbittorrent_wg_server_public_key: "changeme"
qbittorrent_wg_allowed_ips: "0.0.0.0/0"  # changeme
qbittorrent_wg_endpoint: "changeme"
