---
- name: Add Helm repository
  kubernetes.core.helm_repository:
    name: "{{ actual_budget_chart_repo_name }}"
    repo_url: "{{ actual_budget_chart_repo_url }}"

- name: Deploy Actual Budget using Helm
  kubernetes.core.helm:
    name: "{{ actual_budget_release_name }}"
    chart_ref: "{{ actual_budget_chart_repo_name }}/{{ actual_budget_chart_name }}"
    chart_version: "{{ actual_budget_chart_version }}"
    release_namespace: "{{ actual_budget_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    wait: true
