---

# K3S CLUSTER CONFIGURATION

k3s_servers:
  hosts:
    k3s-server1:
      ansible_host: 192.168.30.38
      ansible_python_interpreter: /usr/bin/python3
    k3s-server2:
      ansible_host: 192.168.30.39
      ansible_python_interpreter: /usr/bin/python3
    k3s-server3:
      ansible_host: 192.168.30.40
      ansible_python_interpreter: /usr/bin/python3

k3s_workers:
  hosts:
    k3s-worker1:
      ansible_host: 192.168.30.41
      ansible_python_interpreter: /usr/bin/python3
    k3s-worker2:
      ansible_host: 192.168.30.42
      ansible_python_interpreter: /usr/bin/python3

k3s_cluster:
  children:
    k3s_servers:
    k3s_workers:

ansible_local:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: /home/USER/.local/share/pipx/venvs/ansible/bin/python
