---
immich_enabled: false
immich_namespace: default
immich_release_name: immich
immich_chart_version: "0.9.0"
immich_image_tag: "release"
immich_replica_count: 1

# Postgresql
# internal | cloudnativepg
immich_db_skip_migrations: false
immich_postgresql_source: "internal"
immich_postgresql_create_cluster: false
immich_postgresql_pgvectors_version: "16-v0.3.0"
immich_postgresql_storage_class: "longhorn-single-replica"
immich_postgresql_replicas: "{{ groups['k3s_workers'] | length if groups['k3s_workers'] | length > 1 else 1 }}"

immich_postgresql_override_resources: true
immich_postgresql_resources_requests_memory: "512Mi"
immich_postgresql_resources_requests_cpu: "150m"
immich_postgresql_resources_limits_memory: "1Gi"
immich_postgresql_resources_limits_cpu: "500m"

# Redis
immich_redis_enabled: false
immich_redis_storage_class: "longhorn-single-replica"

# Ingress
immich_ingress_enabled: false
# allow to override without touching global_cluster_issuer
immich_ingress_cluster_issuer: "{{ global_cluster_issuer }}"
immich_ingress_class_name: "{{ global_nginx_class }}"

immich_subdomain: "immich"
immich_ingress_host: "{{ immich_subdomain }}.{{ global_domain_name }}"

# Persistence
# longhorn | pvc
immich_persistence_type: "longhorn"
immich_persistence_longhorn_storage_class: longhorn
# use longhorn if you have low storage requirements or a big longhorn storage
immich_persistence_longhorn_size: "50Gi"
immich_persistence_external_enabled: false
# immich_persistence_external_existing_claim: "nfs-nextcloud"

# Machine learning
immich_machine_learning_enabled: true
immich_machine_learning_persistence_type: pvc
immich_machine_learning_persistence_storage_class: longhorn
immich_machine_learning_resources_limits_cpu: "4000m"
immich_machine_learning_resources_limits_memory: "8Gi"
immich_machine_learning_resources_requests_memory: "512Mi"

# Resources
immich_resources_limits_memory: "4Gi"
immich_resources_limits_cpu: "4000m"
immich_resources_requests_memory: "2Gi"
immich_resources_requests_cpu: "500m"
immich_intel_hw_accel: false

# Affinity
# This settings tries to help immich/redis/postgresql/collabora stay together
immich_affinity_enabled: true
immich_affinity_weight: 80
# This settings tries to help immich/redis/postgresql/collabora avoid another app
immich_anti_affinity_enabled: true
immich_anti_affinity_weight: 80
immich_anti_affinity_target_name: plex-media-server
