# prometheus/tasks/main.yml
---
- name: Add prometheus Helm repository
  kubernetes.core.helm_repository:
    name: "prometheus-community"
    url: "https://prometheus-community.github.io/helm-charts"
    state: present

- name: Deploy prometheus loaded from template (helm)
  kubernetes.core.helm:
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    chart_version: "{{ prometheus_chart_version }}"
    release_namespace: "{{ prometheus_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
