---
- name: Verify persistence configuration when enabled
  ansible.builtin.assert:
    that:
      - >-
        not radarr_persistence_enabled or
        (radarr_existing_claim is defined) or
        (radarr_storage_class is defined and radarr_storage_size is defined)
      - >-
        not radarr_persistence_enabled or
        not (radarr_existing_claim is defined and radarr_storage_class is defined)
    fail_msg: >-
      When persistence is enabled, either:
      - Define an existing claim using radarr_existing_claim
      - OR define both radarr_storage_class and radarr_storage_size
      But not both options simultaneously.

- name: Verify storage size format when defined
  ansible.builtin.assert:
    that:
      - >-
        not radarr_persistence_enabled or
        radarr_existing_claim is defined or
        radarr_storage_size | regex_search('^[0-9]+[MGT]i$')
    fail_msg: "Invalid storage size format. Must be in format: 1Gi, 100Mi, 2Ti, etc."
