# group_vars/ansible_local/actual_budget.yml
---
actual_budget_enabled: true
actual_budget_image_tag: "25.2.1"
actual_budget_storage_size: "5Gi"
actual_budget_storage_class: "longhorn"
actual_budget_ingress_enabled: true
actual_budget_subdomain: "budget-k3s"
# actual_budget_ingress_host: "budget.kube.home" # allow to override
