---
# letsencrypt | selfsigned
cert_manager_certificate_type: "selfsigned"
# staging | production
cert_manager_certificate_letsencrypt_environment: "staging"
# must be left here for other roles to access it
global_cluster_issuer: >-
  {{
    'selfsigned-issuer' if cert_manager_certificate_type == 'selfsigned'
    else (
      'letsencrypt-staging' if cert_manager_certificate_type == 'letsencrypt' and cert_manager_certificate_letsencrypt_environment == 'staging'
      else 'letsencrypt-prod'
    )
  }}

global_nginx_class: "nginx"
global_domain_name: "k3s.home"
