# roles/k3s-nfs/tasks/main.yml
---
- name: Create NFS Static StorageClass
  kubernetes.core.k8s:
    state: present
    template: "nfs-storageclass.yml.j2"
  tags: [storage, storageclass]

- name: Create PersistentVolumes for NFS shares
  kubernetes.core.k8s:
    state: present
    template: "persistentvolume.yml.j2"
  vars:
    item: "{{ share_item }}"
  loop: "{{ nfs_pvc_shares }}"
  loop_control:
    loop_var: share_item
  tags: [storage, pv]

- name: Create PersistentVolumeClaims for NFS shares
  kubernetes.core.k8s:
    state: present
    template: "persistentvolumeclaim.yml.j2"
  vars:
    item: "{{ share_item }}"
  loop: "{{ nfs_pvc_shares }}"
  loop_control:
    loop_var: share_item
  tags: [storage, pvc]
