---
# Base
longhorn_enabled: true
longhorn_namespace: longhorn-system
longhorn_chart_version: 1.8.1-rc2
longhorn_image_tag: ""  # v1.8.1-rc2

# Dashboard
longhorn_dashboard_enabled: true
longhorn_dashboard_subdomain: "longhorn"
longhorn_dashboard_tls: false

# Ingress
longhorn_host: "{{ (longhorn_dashboard_subdomain + '.' + global_domain_name) }}"

# S3 backups
longhorn_minio_backup_enabled: false
# must include http(s), must not include trailing slash ("/")
longhorn_minio_endpoint: "http://IP:PORT"
longhorn_minio_backup_key: ""
longhorn_minio_backup_secret: ""
longhorn_minio_bucket_name: longhorn
# value should not matter unless you use a cloud provider, like AWS S3
# but is required in the format
longhorn_minio_region: "ch-fr-1"
