---

- name: Add longhorn Helm repository
  kubernetes.core.helm_repository:
    name: longhorn
    url: https://charts.longhorn.io
    state: present

- name: Deploy longhorn loaded from template (helm)
  kubernetes.core.helm:
    name: longhorn
    chart_ref: longhorn/longhorn
    chart_version: "{{ longhorn_chart_version }}"
    release_namespace: "{{ longhorn_namespace }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"

- name: Remove default StorageClass local-path.yaml (this is not persistent)
  kubernetes.core.k8s:
    state: absent
    api_version: v1
    kind: StorageClass
    name: local-path

- name: Create StorageClass with 1 replica for CloudNativePG
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'longhorn-single-replica.yaml.j2') | from_yaml }}"

- name: Import S3 bucket related tasks
  ansible.builtin.include_tasks: s3_bucket.yaml
  when: longhorn_minio_backup_enabled
