---
- name: Clean up longhorn PVCs
  ansible.builtin.include_tasks: cleanup_pvc.yml
  vars:
    storage_class_name: "longhorn"
  tags:
    - reset
    - longhorn

- name: Clean up longhorn-single-replica PVCs
  ansible.builtin.include_tasks: cleanup_pvc.yml
  vars:
    storage_class_name: "longhorn-single-replica"
  tags:
    - reset
    - longhorn

- name: Ensure Longhorn deletion Setting is applied
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: longhorn.io/v1beta1
      kind: Setting
      metadata:
        name: deleting-confirmation-flag
        namespace: longhorn-system
      value: "true"
  register: setting_result
  ignore_errors: true  # In case the CRD is already gone
  tags:
    - reset
    - longhorn

- name: Wait for Setting to be applied
  ansible.builtin.pause:
    seconds: 15
  when: setting_result is succeeded
  tags:
    - reset
    - longhorn

- name: Uninstall longhorn (helm)
  kubernetes.core.helm:
    name: longhorn
    release_namespace: "{{ longhorn_namespace }}"
    state: absent
    wait: true
    wait_timeout: 600s  # 10 minutes timeout for clean deletion
  tags:
    - reset
    - longhorn
