# roles/k8up/defaults/main.yml
---
# General settings
k8up_default_namespace: "default"
k8up_wait_timeout: 180
k8up_workload_default_replicas: 1

# K8up Helm Configuration
k8up_chart_version: "4.8.3"
k8up_chart_namespace: "k8up-system"

# S3 Backend configuration
minio_endpoint: "http://changeme.com:port"
minio_access_key: "changeme"
minio_secret_key: "changeme"
minio_repository_password: "changeme"

# Backup configuration
backup_tags: []
backup_failed_jobs_history_limit: 2
backup_successful_jobs_history_limit: 2

# Restore configuration
restore_pod_security_context:
  fsGroup: 33  # www-data for example for Nextcloud
  fsGroupChangePolicy: OnRootMismatch

# Operation arrays (to be filled by playbook)
k8up_backup_list: []
# Example structure:
# k8up_backup_list:
#   - name: "immich"
#     pvc_name: "nfs-immich"
#     psql_pod: "immich-postgresql-0"
#     deployment_name: "immich-server"
#     run_as_user: 0  # root
#   - name: "plex"
#     pvc_name: "pms-config-plex-media-server-0"
#     statefulset_name: "plex-media-server"
#     run_as_user: 1000

k8up_restore_pvcs: []
# Example structure:
# k8up_restore_pvcs:
#   - name: "postgresql-data"
#     namespace: "database"
#     workload_type: StatefulSet
#     workload_name: "postgresql"
#     workload_replicas: 3
#     minio_bucket: "nextcloud-config-backup"
#     tags: ["database"]
#     fs_group: 999

# Temp migration variables
migration_namespace: default
temp_postgres_password: "temporaryPassword123"
source_database_name: "mydb"
sql_dump_path: "/path/to/dump.sql"
cnpg_cluster_name: "production-db"
cnpg_instances: 3
cnpg_storage_size: "10Gi"
temp_storage_size: "10Gi"
