---
- name: Create PostgreSQL credentials secret
  kubernetes.core.k8s:
    state: present
    template: templates/cnpg-db-secret.yaml.j2
  tags:
    - nextcloud
    - database

- name: Create PostgreSQL cluster
  kubernetes.core.k8s:
    state: present
    template: templates/cnpg-cluster.yaml.j2
  tags:
    - nextcloud
    - database

- name: Wait for PostgreSQL cluster to be ready
  kubernetes.core.k8s_info:
    api_version: postgresql.cnpg.io/v1
    kind: Cluster
    name: nextcloud-db
    namespace: "{{ nextcloud_namespace }}"
    wait: true
    wait_timeout: 150
    wait_condition:
      type: Ready
      status: "True"
      reason: ClusterIsReady
  register: pg_cluster
  failed_when: >-
    pg_cluster.resources is not defined or
    pg_cluster.resources | length == 0
  tags:
    - nextcloud
    - database
