# roles/k8up/tasks/main.yml
---
- name: Verify prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yml

- name: Process individual backups
  ansible.builtin.include_tasks:
    file: backup.yml
  when: k8up_backup_list is defined and k8up_backup_list | length > 0
  loop: "{{ k8up_backup_list }}"
  loop_control:
    loop_var: backup_item
    label: "{{ backup_item.name }}"

- name: Process postgresql migration
  ansible.builtin.include_tasks:
    file: migrate_postgresql.yml
  when: k8up_restore_psql_list is defined and k8up_restore_psql_list | length > 0
  loop: "{{ k8up_restore_psql_list }}"
  loop_control:
    loop_var: restore_item
    label: "{{ restore_item.name }}"

- name: Process immich postgresql migration
  ansible.builtin.include_tasks:
    file: migrate_immich_postgresql.yml
  when: k8up_restore_immich is defined and k8up_restore_immich | length > 0
  loop: "{{ k8up_restore_immich }}"
  loop_control:
    loop_var: restore_item
    label: "{{ restore_item.name }}"

- name: Process individual restores
  ansible.builtin.include_tasks:
    file: restore.yml
  when: k8up_restore_list is defined and k8up_restore_list | length > 0
  loop: "{{ k8up_restore_list }}"
  loop_control:
    loop_var: restore_item
    label: "{{ restore_item.name }}"
