# roles/k8up/tasks/main.yml
---
- name: Verify prerequisites
  ansible.builtin.include_tasks:
    file: prerequisites.yml

- name: Process individual backups
  ansible.builtin.include_tasks:
    file: backup.yml
  loop: "{{ k8up_backup_list }}"
  loop_control:
    loop_var: backup_item
    label: "{{ backup_item.name }}"

# - name: Execute restore tasks
#   ansible.builtin.include_tasks:
#     file: restore.yml
#   when: k8up_restore_pvcs | length > 0

# - name: Migrate PostgreSQL to CNPG
#   ansible.builtin.include_tasks:
#     migrate_to_cnpg.yml
#   when: k8up_restore_psqls | length > 0
  # vars:
  #   migration_namespace: "default"
  #   source_database_name: "nextcloud"
  #   sql_dump_path: "dump.sql"
  #   cnpg_cluster_name: "nextcloud-tmp-db"
