# tasks/migrate_to_cnpg.yml
---
- name: Verify required variables are defined
  ansible.builtin.assert:
    that:
      - restore_item.namespace is defined
      - restore_item.snapshot_id is defined
      - restore_item.database_name is defined
      - restore_item.database_user is defined
      - restore_item.database_credentials_secret is defined
      - restore_item.cnpg_cluster_name is defined
    fail_msg: "Missing required variables for database migration of {{ restore_item.name }}"

- name: Get database password from existing secret
  kubernetes.core.k8s_info:
    api_version: v1
    kind: Secret
    name: "{{ restore_item.database_credentials_secret }}"
    namespace: "{{ restore_item.namespace }}"
  register: db_secret

- name: Set database password from secret
  ansible.builtin.set_fact:
    db_password: "{{ db_secret.resources[0].data.password | b64decode }}"

- name: Add Bitnami helm repository
  kubernetes.core.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami

- name: Create temporary restore PVC
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: "temp-restore-{{ restore_item.name }}"
        namespace: "{{ restore_item.namespace }}"
        labels:
          app: "temp-restore-{{ restore_item.name }}"
          created-by: ansible
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ restore_item.temp_pvc_storage_size | default('10Gi') }}"
        storageClassName: "{{ storage_class | default('longhorn') }}"

- name: Create K8up restore job
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: k8up.io/v1
      kind: Restore
      metadata:
        name: "{{ restore_item.name }}-psql"
        namespace: "{{ restore_item.namespace }}"
      spec:
        snapshot: "{{ restore_item.snapshot_id | default(omit) | string }}"
        podSecurityContext:
          runAsUser: "{{ restore_item.run_as_user | default(omit) | int }}"
          runAsGroup: "{{ restore_item.run_as_user | default(omit) | int }}"
          fsGroup: "{{ restore_item.run_as_user | default(omit) | int }}"
          fsGroupChangePolicy: OnRootMismatch
        backend:
          repoPasswordSecretRef:
            name: backup-repo
            key: password
          s3:
            endpoint: "{{ minio_endpoint }}"
            bucket: "{{ minio_bucket }}"
            accessKeyIDSecretRef:
              name: minio-credentials
              key: username
            secretAccessKeySecretRef:
              name: minio-credentials
              key: password
        restoreMethod:
          folder:
            claimName: "temp-restore-{{ restore_item.name }}"

- name: "Wait for restore to complete: {{ restore_item.name }}"
  kubernetes.core.k8s:
    api_version: k8up.io/v1
    kind: Restore
    name: "{{ restore_item.name }}-psql"
    namespace: "{{ restore_item.namespace }}"
    wait: true
    wait_condition:
      type: Completed
      status: "True"
    wait_timeout: 10800  # 3h
  register: restore_status

# - name: Debug temp PostgreSQL values
#   ansible.builtin.debug:
#     msg: "{{ temp_postgres_values | to_yaml }}"

- name: Deploy temporary PostgreSQL with Helm
  kubernetes.core.helm:
    name: "temp-postgres-{{ restore_item.name }}"
    chart_ref: bitnami/postgresql
    chart_version: "16.4.14"  # Specify a stable version
    release_namespace: "{{ restore_item.namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'temp-postgresql-values.yml.j2') | from_yaml }}"
    wait: true
    wait_timeout: 5m

# https://immich.app/docs/administration/backup-and-restore/#manual-backup-and-restore
- name: Fix SQL dump for immich
  kubernetes.core.k8s_exec:
    namespace: "{{ restore_item.namespace }}"
    pod: "temp-postgres-{{ restore_item.name }}-postgresql-0"
    container: postgresql
    command: sh -c "sed \"s/SELECT pg_catalog.set_config('search_path', '', false);/SELECT pg_catalog.set_config('search_path', 'public, pg_catalog', true);/g\" \"/bitnami/postgresql/default-postgresql-{{ restore_item.name }}.sql\" > \"/bitnami/postgresql/default-postgresql-{{ restore_item.name }}.sql.fixed\""
  register: restore_result
  failed_when: restore_result.rc != 0
  when: restore_item.name == "immich"

- name: Restore SQL dump to temporary PostgreSQL
  kubernetes.core.k8s_exec:
    namespace: "{{ restore_item.namespace }}"
    pod: "temp-postgres-{{ restore_item.name }}-postgresql-0"
    container: postgresql
    command: sh -c 'psql --username="{{ restore_item.database_user }}" --dbname="postgres" -f "/bitnami/postgresql/default-postgresql-{{ restore_item.name }}.sql.fixed"'
  register: restore_result
  failed_when: >
    restore_result.rc != 0 and
    restore_result.rc != 137 and
    not ('ERROR:  current user cannot be dropped' in restore_result.stderr) and
    not ('ERROR:  role "immich" already exists' in restore_result.stderr)
  when: restore_item.name == "immich"

- name: Restore SQL dump to temporary PostgreSQL
  kubernetes.core.k8s_exec:
    namespace: "{{ restore_item.namespace }}"
    pod: "temp-postgres-{{ restore_item.name }}-postgresql-0"
    container: postgresql
    command: sh -c 'PGPASSWORD="{{ db_password }}" psql -U "{{ restore_item.database_user }}" -d "{{ restore_item.database_name }}" -f "/bitnami/postgresql/default-postgresql-{{ restore_item.name }}.sql.fixed"'
  register: restore_result
  failed_when: restore_result.rc != 0
  when: restore_item.name != "immich"

- name: Remove existing cluster
  kubernetes.core.k8s:
    state: absent
    api_version: postgresql.cnpg.io/v1
    kind: Cluster
    name: "{{ restore_item.cnpg_cluster_name }}"
    namespace: "{{ restore_item.namespace }}"
    wait: true

# - name: Generate debug YAML file
#   ansible.builtin.template:
#     src: templates/cnpg-import-cluster.yml.j2
#     dest: /tmp/cnpg-import-cluster.yml
#     mode: '0644'
#   diff: true  # This will show the difference in the output

- name: Create import DB credentials secret
  kubernetes.core.k8s:
    state: present
    template: templates/cnpg-existing-db-secret.yml.j2

- name: Apply CNPG import definition
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'cnpg-import-cluster.yml.j2') | from_yaml }}"

- name: Wait for PostgreSQL cluster to be ready
  kubernetes.core.k8s_info:
    api_version: postgresql.cnpg.io/v1
    kind: Cluster
    name: "{{ restore_item.cnpg_cluster_name }}"
    namespace: "{{ restore_item.namespace }}"
    wait: true
    wait_timeout: 180
    wait_condition:
      type: Ready
      status: "True"
      reason: ClusterIsReady
  register: pg_cluster
  failed_when: >-
    pg_cluster.resources is not defined or
    pg_cluster.resources | length == 0

# - name: Uninstall Bitnami Postgres (helm)
#   kubernetes.core.helm:
#     name: "temp-postgres-{{ restore_item.name }}"
#     release_namespace: "{{ restore_item.namespace }}"
#     state: absent
#     wait: true

# - name: Clean up temporary Restore
#   kubernetes.core.k8s:
#     state: absent
#     kind: Restore
#     api_version: k8up.io/v1
#     name: "{{ restore_item.name }}-psql"
#     namespace: "{{ restore_item.namespace }}"
#     wait: true

# - name: Clean up temporary PVC
#   kubernetes.core.k8s:
#     state: absent
#     kind: PersistentVolumeClaim
#     api_version: v1
#     name: "temp-restore-{{ restore_item.name }}"
#     namespace: "{{ restore_item.namespace }}"
