---
- name: Extract number of restored files from logs
  ansible.builtin.set_fact:
    restored_files_count: "{{ all_pod_logs | regex_search('Restored (\\d+) files/dirs', '\\1') | first }}"
  when: all_pod_logs is defined

- name: Display restore summary
  ansible.builtin.debug:
    msg:
      title: "Restore Summary"
      statistics:
        restored_files: "{{ restored_files_count }}"
  when: restored_files_count is defined
