---

- name: Validate PostgreSQL source configuration
  ansible.builtin.assert:
    that:
      - paperless_database_source in ['internal', 'cloudnativepg']
    fail_msg: "Invalid postgresql source '{{ paperless_database_source }}'. \
               Must be one of: internal or cloudnativepg"
    success_msg: "PostgreSQL source '{{ paperless_database_source }}' is valid"

- name: Add paperless helm repository
  kubernetes.core.helm_repository:
    name: gabe565
    repo_url: https://charts.gabe565.com

- name: Configure CloudNativePG
  ansible.builtin.import_tasks: cloudnative_pg.yml
  when:
    - cloudnative_pg_enabled | bool
    - paperless_database_source == "cloudnativepg"

- name: Create NFS PV and PVC resources
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'nfs-resources.yaml.j2') | from_yaml_all | list }}"
  when: paperless_nfs_use_enabled

# - name: Generate debug YAML file
#   ansible.builtin.template:
#     src: templates/values.yaml.j2
#     dest: /tmp/paperless_values_debug.yaml
#     mode: '0644'
#   diff: true  # This will show the difference in the output

- name: Deploy Paperless using Helm
  kubernetes.core.helm:
    name: "{{ paperless_release_name }}"
    chart_ref: gabe565/paperless-ngx
    chart_version: "{{ paperless_chart_version }}"
    release_namespace: "{{ paperless_namespace }}"
    values: "{{ lookup('template', 'values.yaml.j2') | from_yaml }}"
    create_namespace: true
    update_repo_cache: true
    wait: true
