---
- name: Uninstall actual_budget (helm)
  kubernetes.core.helm:
    name: "{{ paperless_release_name }}"
    release_namespace: "{{ paperless_namespace }}"
    state: absent
    wait: true
  tags:
    - reset
    - paperless

- name: Delete Cluster
  kubernetes.core.k8s:
    state: absent
    kind: Cluster
    name: paperless-db
    namespace: "{{ paperless_namespace }}"
  when: paperless_database_source == "cloudnativepg"
  tags:
    - reset
    - paperless

- name: Delete NFS PV and PVC resources
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'nfs-resources.yaml.j2') | from_yaml_all | list }}"
  tags:
    - reset
    - paperless
