---
- name: Create PostgreSQL credentials secret
  kubernetes.core.k8s:
    state: present
    template: templates/cnpg-db-secret.yml.j2
  tags:
    - gitea
    - database

- name: Set dynamic backup path
  ansible.builtin.set_fact:
    gitea_postgresql_backup_destination_path: >-
      s3://{{ gitea_postgresql_backup_s3_bucket }}/
  when:
    - gitea_postgresql_backup_enabled | bool
    - gitea_postgresql_backup_destination_path | length == 0
  tags:
    - gitea
    - database

- name: Create S3 backup credentials secret
  kubernetes.core.k8s:
    state: present
    template: templates/s3-backup-credentials-secret.yml.j2
  when:
    - gitea_postgresql_backup_enabled | bool
  tags:
    - gitea
    - database

- name: Create PostgreSQL cluster
  kubernetes.core.k8s:
    state: present
    template: templates/cnpg-cluster.yml.j2
  tags:
    - gitea
    - database

- name: Wait for PostgreSQL cluster to be ready
  kubernetes.core.k8s_info:
    api_version: postgresql.cnpg.io/v1
    kind: Cluster
    name: gitea-db
    namespace: "{{ gitea_namespace }}"
    wait: true
    wait_timeout: 300
    wait_condition:
      type: Ready
      status: "True"
      reason: ClusterIsReady
  register: pg_cluster
  failed_when: >-
    pg_cluster.resources is not defined or
    pg_cluster.resources | length == 0
  tags:
    - gitea
    - database
