---
- name: Read /proc/cpuinfo
  ansible.builtin.slurp:
    src: /proc/cpuinfo
  register: cpuinfo_content
  failed_when: false

- name: Read /proc/device-tree/model
  ansible.builtin.slurp:
    src: /proc/device-tree/model
  register: device_tree_model_content
  failed_when: false

- name: Detect Raspberry Pi from hardware info
  ansible.builtin.set_fact:
    is_raspberrypi_cpuinfo: >-
      {{ (cpuinfo_content.content | b64decode)
         is regex('Raspberry Pi|BCM2708|BCM2709|BCM2835|BCM2836') }}
    is_raspberrypi_model: >-
      {{ (device_tree_model_content.content | b64decode) is regex('Raspberry Pi')
         if device_tree_model_content.content is defined else false }}

- name: Set raspberry_pi fact to true
  ansible.builtin.set_fact:
    raspberry_pi: true
  when: is_raspberrypi_cpuinfo or is_raspberrypi_model

- name: Set detected_distribution to Raspbian (ARM64 on Raspbian, Debian Buster/Bullseye/Bookworm)
  ansible.builtin.set_fact:
    detected_distribution: Raspbian
  vars:
    allowed_descriptions:
      - "[Rr]aspbian.*"
      - Debian.*buster
      - Debian.*bullseye
      - Debian.*bookworm
  when:
    - ansible_facts.architecture is search("aarch64")
    - raspberry_pi|default(false)
    - ansible_facts.lsb.description|default("") is match(allowed_descriptions | join('|'))

- name: Set detected_distribution to Raspbian (ARM64 on Debian Bookworm)
  ansible.builtin.set_fact:
    detected_distribution: Raspbian
  when:
    - ansible_facts.architecture is search("aarch64")
    - raspberry_pi|default(false)
    - ansible_facts.lsb.description|default("") is match("Debian.*bookworm")

- name: Set detected_distribution_major_version
  ansible.builtin.set_fact:
    detected_distribution_major_version: "{{ ansible_facts.lsb.major_release }}"
  when:
    - detected_distribution | default("") == "Raspbian"

- name: Execute OS related tasks on the Raspberry Pi - {{ action_ }}
  ansible.builtin.include_tasks: "{{ item }}"
  with_first_found:
    - "{{ action_ }}/{{ detected_distribution }}-{{ detected_distribution_major_version }}.yml"
    - "{{ action_ }}/{{ detected_distribution }}.yml"
    - "{{ action_ }}/{{ ansible_facts['distribution'] }}-{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ action_ }}/{{ ansible_facts['distribution'] }}.yml"
    - "{{ action_ }}/default.yml"
  vars:
    action_: >-
      {% if state == "present" %}setup{% else %}teardown{% endif %}
  when:
    - raspberry_pi|default(false)
