---
- name: Create the k3s directory
  ansible.builtin.file:
    path: /etc/systemd/system/k3s.service.d
    state: directory
    mode: "0755"

- name: Template HTTP Proxy
  ansible.builtin.template:
    src: http_proxy.conf.j2
    dest: /etc/systemd/system/k3s.service.d/http_proxy.conf
    mode: "0644"
