---
galaxy_info:
  role_name: k3s_server_join
  author: kriegalex
  description: Join new k3s server nodes to an existing cluster
  license: MIT
  min_ansible_version: "2.15"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: EL
      versions:
        - "8"
        - "9"
  galaxy_tags:
    - k3s
    - kubernetes
    - cluster
    - join

dependencies: []
