---
- name: Include validation tasks
  ansible.builtin.import_tasks: validation.yml

- name: Add flaresolverr helm repository
  kubernetes.core.helm_repository:
    name: "{{ flaresolverr_repository_name }}"
    repo_url: "{{ flaresolverr_repository_url }}"

# - name: Create temporary values file for debug
#   ansible.builtin.template:
#     src: templates/values.yml.j2
#     dest: "/tmp/flaresolverr-values.yaml"
#     mode: "644"
#   diff: true  # This will show the difference in the output

- name: Deploy flaresolverr helm chart
  kubernetes.core.helm:
    name: flaresolverr
    chart_ref: "{{ flaresolverr_repository_name }}/{{ flaresolverr_chart_name }}"
    release_namespace: "{{ flaresolverr_namespace }}"
    chart_version: "{{ flaresolverr_chart_version }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
    wait: true
    state: present

- name: Display libseccomp2 version check reminder
  ansible.builtin.debug:
    msg: "IMPORTANT: If running FlareSolverr on Debian/Ubuntu nodes, ensure libseccomp2 version 2.5.x is installed."
