---
- name: Verify persistence configuration when enabled
  ansible.builtin.assert:
    that:
      - >-
        not flaresolverr_persistence_enabled or
        (flaresolverr_existing_claim is defined) or
        (flaresolverr_storage_class is defined and flaresolverr_storage_size is defined)
      - >-
        not flaresolverr_persistence_enabled or
        not (flaresolverr_existing_claim is defined and flaresolverr_storage_class is defined)
    fail_msg: >-
      When persistence is enabled, either:
      - Define an existing claim using flaresolverr_existing_claim
      - OR define both flaresolverr_storage_class and flaresolverr_storage_size
      But not both options simultaneously.

- name: Verify storage size format when defined
  ansible.builtin.assert:
    that:
      - >-
        not flaresolverr_persistence_enabled or
        flaresolverr_existing_claim is defined or
        flaresolverr_storage_size | regex_search('^[0-9]+[MGT]i$')
    fail_msg: "Invalid storage size format. Must be in format: 1Gi, 100Mi, 2Ti, etc."
