---
- name: Delete GPU plugin
  ansible.builtin.command: kubectl delete -k 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/gpu_plugin/overlays/nfd_labeled_nodes?ref={{ intel_gpu_plugin_app_version }}' --ignore-not-found=true
  changed_when: true
  tags:
    - reset
    - gpu
    - intel_gpu_plugin

- name: Delete NodeFeatureRules
  ansible.builtin.command: kubectl delete -k 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd/overlays/node-feature-rules?ref={{ intel_gpu_plugin_app_version }}' --ignore-not-found=true
  changed_when: true
  tags:
    - reset
    - gpu
    - intel_gpu_plugin

- name: Delete NFD base deployment
  ansible.builtin.command: kubectl delete -k 'https://github.com/intel/intel-device-plugins-for-kubernetes/deployments/nfd?ref={{ intel_gpu_plugin_app_version }}' --ignore-not-found=true
  changed_when: true
  tags:
    - reset
    - gpu
    - intel_gpu_plugin
