# roles/k3s-nfs/defaults/main.yml
---
nfs_pvc_enabled: false
# NFS server details
nfs_version: 4.2
nfs_pvc_server: "10.0.0.2"
nfs_pvc_root_path: "/mnt/user"

# Default reclaim policy for PVs (Retain is safer for homelab data)
nfs_pvc_reclaim_policy: "Retain"

# Default access mode (ReadWriteMany for shared access)
nfs_pvc_access_mode: "ReadWriteMany"

nfs_pvc_shares: []
