---

- name: Check if Helm is installed
  hosts: ansible_local
  connection: local
  gather_facts: false
  tasks:
    - name: Checking Helm version
      ansible.builtin.command: "helm version --client"
      register: helm_version
      failed_when: helm_version.rc != 0 and helm_version.stderr != ""
      changed_when: false

- name: Include Helm install roles
  hosts: ansible_local
  connection: local
  gather_facts: false
  roles:
    - role: nfs_client
      when: nfs_client_enabled
      tags:
        - nfs
    - role: nfs_pvc
      when: nfs_pvc_enabled
      tags:
        - nfs
    - role: intel_gpu_plugin
      when: intel_gpu_plugin_enabled
      tags:
        - gpu
    - role: cloudnative_pg
      when: cloudnative_pg_enabled
      tags:
        - database
        - cloudnativepg
    - role: plex
      when: plex_enabled
      tags:
        - plex
        - media
    - role: nextcloud
      when: nextcloud_enabled
      tags:
        - nextcloud
        - cloud
    - role: immich
      when: immich_enabled
      tags:
        - immich
        - photo
    - role: paperless
      when: paperless_enabled
      tags:
        - paperless
        - document
    - role: actual_budget
      when: actual_budget_enabled
      tags:
        - actual_budget
        - finance
    - role: gitea
      when: gitea_enabled
      tags:
        - git
        - gitea
    - role: overseerr
      when: overseerr_enabled
      tags:
        - overseerr
        - media
    - role: prowlarr
      when: prowlarr_enabled
      tags:
        - prowlarr
        - media
    - role: radarr
      when: radarr_enabled
      tags:
        - radarr
        - media
    - role: sonarr
      when: sonarr_enabled
      tags:
        - sonarr
        - media
    - role: flaresolverr
      when: flaresolverr_enabled
      tags:
        - flaresolverr
        - media
    # - role: qbittorrent
    #   when: qbittorrent.enabled
    #   tags:
    #     - qbittorrent
    # - role: home-assistant
    #   when: home_assistant.enabled
    #   tags:
    #     - home-assistant
