---

- name: Reset Apps
  hosts: ansible_local
  connection: local
  gather_facts: false
  tasks:
    - name: Uninstall qbittorrent
      ansible.builtin.include_role:
        name: qbittorrent
        tasks_from: reset
      tags:
        - qbittorrent
    - name: Uninstall flaresolverr
      ansible.builtin.include_role:
        name: flaresolverr
        tasks_from: reset
      tags:
        - flaresolverr
        - media
    - name: Uninstall prowlarr
      ansible.builtin.include_role:
        name: prowlarr
        tasks_from: reset
      tags:
        - prowlarr
        - media
    - name: Uninstall sonarr
      ansible.builtin.include_role:
        name: sonarr
        tasks_from: reset
      tags:
        - sonarr
        - media
    - name: Uninstall radarr
      ansible.builtin.include_role:
        name: radarr
        tasks_from: reset
      tags:
        - radarr
        - media
    - name: Uninstall overseerr
      ansible.builtin.include_role:
        name: overseerr
        tasks_from: reset
      tags:
        - overseerr
        - media
    - name: Uninstall gitea
      ansible.builtin.include_role:
        name: gitea
        tasks_from: reset
      tags:
        - gitea
    - name: Uninstall actual_budget
      ansible.builtin.include_role:
        name: actual_budget
        tasks_from: reset
      tags:
        - actual_budget
    - name: Uninstall paperless
      ansible.builtin.include_role:
        name: paperless
        tasks_from: reset
      tags:
        - paperless
    - name: Uninstall immich
      ansible.builtin.include_role:
        name: immich
        tasks_from: reset
      tags:
        - immich
    - name: Uninstall nextcloud
      ansible.builtin.include_role:
        name: nextcloud
        tasks_from: reset
      tags:
        - nextcloud
    - name: Uninstall plex
      ansible.builtin.include_role:
        name: plex
        tasks_from: reset
      tags:
        - plex
        - media
    - name: Uninstall nfs_client
      ansible.builtin.include_role:
        name: nfs_client
        tasks_from: reset
      tags:
        - nfs_client
    - name: Uninstall nfs_pvc
      ansible.builtin.include_role:
        name: nfs_pvc
        tasks_from: reset
      tags:
        - nfs_pvc
    - name: Uninstall k8up
      ansible.builtin.include_role:
        name: k8up
        tasks_from: reset
      tags:
        - k8up
        - backup
    - name: Uninstall prometheus-grafana stack
      ansible.builtin.include_role:
        name: prometheus
        tasks_from: reset
      tags:
        - prometheus
        - grafana
    - name: Uninstall intel_gpu_plugin
      ansible.builtin.include_role:
        name: intel_gpu_plugin
        tasks_from: reset
      tags:
        - gpu
        - intel_gpu_plugin
    - name: Uninstall cloudnative_pg
      ansible.builtin.include_role:
        name: cloudnative_pg
        tasks_from: reset
      tags:
        - cloudnative_pg
    - name: Uninstall longhorn
      ansible.builtin.include_role:
        name: longhorn
        tasks_from: reset
      tags:
        - longhorn
    - name: Uninstall cert_manager
      ansible.builtin.include_role:
        name: cert_manager
        tasks_from: reset
      tags:
        - cert_manager
    - name: Uninstall ingress_nginx
      ansible.builtin.include_role:
        name: ingress_nginx
        tasks_from: reset
      tags:
        - ingress_nginx
