# restore-playbook.yml
---
- name: Restore multiple PVCs
  hosts: ansible_local
  vars:
    k8up_restore_list:
      - name: "prowlarr"
        pvc_name: "prowlarr"
        deployment_name: "prowlarr"
        run_as_user: 1000  # hotio
        repo_bucket: "prowlarr"
      - name: "sonarr"
        pvc_name: "sonarr-tv"
        deployment_name: "sonarr-tv"
        run_as_user: 1000  # hotio
        repo_bucket: "sonarr-tv"
      - name: "sonarr-anime"
        pvc_name: "sonarr-anime"
        deployment_name: "sonarr-anime"
        run_as_user: 1000  # hotio
        repo_bucket: "sonarr-anime"
      - name: "radarr"
        pvc_name: "radarr"
        deployment_name: "radarr"
        run_as_user: 1000  # hotio
        repo_bucket: "radarr"
      - name: "actual-budget"
        pvc_name: "actual-budget-pvc"
        deployment_name: "actual-budget"
        run_as_user: 0  # root
        repo_bucket: "actual-budget"
      - name: "overseerr"
        pvc_name: "overseerr-config"
        deployment_name: "overseerr"
        run_as_user: 1000  # node
        repo_bucket: "overseerr-config"
      - name: "qbittorrent"
        pvc_name: "qbittorrent-config"
        deployment_name: "qbittorrent"
        run_as_user: 1000  # hotio
        repo_bucket: "qbit-qbittorrent-config"
      - name: "plex"
        pvc_name: "pms-config-plex-media-server-0"
        statefulset_name: "plex-media-server"
        run_as_user: 1000
        repo_bucket: "pms-config-plex-media-server-0"
      - name: "nextcloud"
        pvc_name: "nextcloud-nextcloud"
        deployment_name: "nextcloud"
        run_as_user: 33  # www-data
        repo_bucket: "nextcloud-config"
      - name: "paperless"
        pvc_name: "paperless-media-pvc"
        deployment_name: "paperless-ngx"
        run_as_user: 1000  # paperless
        repo_bucket: "paperless-media"
    k8up_restore_psql_list:
      - name: "nextcloud"
        namespace: "default"
        repo_bucket: "nextcloud-postgresql-0"
        run_as_user: 33  # www-data
        database_name: "nextcloud"
        database_user: "nextcloud"
        database_password: "{{ vault_nextcloud_db_password }}"
        cnpg_cluster_name: "nextcloud-db"
        cnpg_instances: 2
        cnpg_storage_size: "10Gi"
        cnpg_storage_class: "longhorn-single-replica"
        cnpg_image_name: "ghcr.io/cloudnative-pg/postgresql:16.4"
      - name: "paperless"
        namespace: "default"
        repo_bucket: "paperless-ngx-postgresql-0"
        run_as_user: 1000  # paperless
        database_name: "paperless"
        database_user: "paperless"
        database_password: "{{ vault_paperless_db_password }}"
        cnpg_cluster_name: "paperless-db"
        cnpg_instances: 2
        cnpg_storage_size: "10Gi"
        cnpg_storage_class: "longhorn-single-replica"
        cnpg_image_name: "ghcr.io/cloudnative-pg/postgresql:16.4"
      - name: "gitea"
        namespace: "default"
        repo_bucket: "gitea-postgresql-0"
        run_as_user: 1000  # git
        database_name: "gitea"
        database_user: "gitea"
        database_password: "{{ vault_gitea_db_password }}"
        cnpg_cluster_name: "gitea-db"
        cnpg_instances: 2
        cnpg_storage_size: "10Gi"
        cnpg_storage_class: "longhorn-single-replica"
        cnpg_image_name: "ghcr.io/cloudnative-pg/postgresql:16.4"
    k8up_restore_immich:
      - name: "immich"
        namespace: "default"
        repo_bucket: "immich-postgresql-0"
        run_as_user: 0  # root
        database_name: "immich"
        database_user: "immich"
        database_password: "{{ vault_immich_user_password }}"
        cnpg_cluster_name: "immich-db"
        cnpg_instances: 1  # bug in pgvector <0.4
        cnpg_storage_size: "10Gi"
        cnpg_storage_class: "longhorn-single-replica"
        cnpg_image_name: "ghcr.io/tensorchord/cloudnative-pgvecto.rs:14-v0.2.0"
  roles:
    - role: k8up
      tags: [target, k8up, restore]
