---

- name: Pre tasks
  hosts: all
  pre_tasks:
    - name: Verify Ansible is version 2.11 or above. (If this fails you may need to update Ansible)
      ansible.builtin.assert:
        that: ansible_version.full is version_compare('2.11', '>=')
        msg: >
          "Ansible is out of date. See here for more info: https://docs.technotim.live/posts/ansible-automation/"

- name: Prepare k3s nodes
  hosts: k3s_cluster
  gather_facts: true
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: prereq
      become: true
    - role: download
      become: true
    - role: raspberrypi
      become: true
    - role: k3s_custom_registries
      become: true
      when: custom_registries

- name: Setup k3s servers
  hosts: k3s_servers
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_server
      become: true

- name: Setup k3s agents
  hosts: k3s_workers
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_agent
      become: true

- name: Configure k3s cluster
  hosts: k3s_servers
  environment: "{{ proxy_env | default({}) }}"
  roles:
    - role: k3s_server_post
      become: true

- name: Copying kubeconfig file
  hosts: k3s_servers
  roles:
    - role: fetch

- name: Include base ingress helm install after k3s installation
  ansible.builtin.import_playbook: base_ingress.yml
  tags: ingress

- name: Include base storage helm install after k3s installation
  ansible.builtin.import_playbook: base_storage.yml
  tags: storage

- name: Include base apps helm install after k3s installation
  ansible.builtin.import_playbook: base_apps.yml
  tags: apps
