---

- name: Create private key for CA
  community.crypto.openssl_privatekey:
    path: "{{ cert_manager_key_path }}"

- name: Create certificate signing request (CSR) for CA certificate
  community.crypto.openssl_csr_pipe:
    privatekey_path: "{{ cert_manager_key_path }}"
    common_name: "{{ cert_manager_certificate_selfsigned_common_name }}"
    country_name: "{{ cert_manager_certificate_selfsigned_country_name }}"
    organization_name: "{{ cert_manager_certificate_selfsigned_organization_name }}"
    use_common_name_for_san: false  # since we do not specify SANs, don't use CN as a SAN
    basic_constraints:
      - 'CA:TRUE'
    basic_constraints_critical: true
    key_usage:
      - keyCertSign
    key_usage_critical: true
  register: ca_csr

- name: Create self-signed CA certificate from CSR
  community.crypto.x509_certificate:
    path: "{{ cert_manager_cert_path }}"
    csr_content: "{{ ca_csr.csr }}"
    privatekey_path: "{{ cert_manager_key_path }}"
    provider: selfsigned

- name: Deploy cert-manager secret from template file
  kubernetes.core.k8s:
    state: present
    template: 'secrets/selfsigned-secret.yaml.j2'

- name: Deploy self-signed ClusterIssuer from template file
  kubernetes.core.k8s:
    state: present
    template: 'issuers/selfsigned-issuer.yaml.j2'

- name: Deploy self-signed Certificate from template file
  kubernetes.core.k8s:
    state: present
    template: 'certificates/selfsigned-certificate.yaml.j2'