---
- name: Include validation tasks
  ansible.builtin.import_tasks: validation.yml

- name: Add sonarr helm repository
  kubernetes.core.helm_repository:
    name: "{{ sonarr_repository_name }}"
    repo_url: "{{ sonarr_repository_url }}"

# - name: Create temporary values file for debug
#   ansible.builtin.template:
#     src: templates/values.yml.j2
#     dest: "/tmp/sonarr-values.yaml"
#     mode: "644"
#   diff: true  # This will show the difference in the output

- name: Create Sonarr namespace
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ sonarr_namespace }}"
  when: sonarr_enabled

- name: Create NFS PV and PVC for additional volumes
  ansible.builtin.include_role:
    name: nfs_pvc
    tasks_from: create_pvc
  when: sonarr_enabled and nfs_pvc_items | length > 0
  vars:
    nfs_pvc_items: >-
      {{ sonarr_additional_volumes |
        selectattr('nfs.enabled', 'defined') |
        selectattr('nfs.enabled') |
        map('combine', {'__tmp_namespace': sonarr_namespace}) |
        map('json_query', '{
          name: claim_name,
          namespace: __tmp_namespace,
          server: nfs.server,
          path: nfs.path,
          size: nfs.size,
          access_mode: nfs.access_mode,
          reclaim_policy: nfs.reclaim_policy
          }') |
        list }}

- name: Deploy sonarr helm chart
  kubernetes.core.helm:
    name: "{{ sonarr_release_name }}"
    chart_ref: "{{ sonarr_repository_name }}/{{ sonarr_chart_name }}"
    release_namespace: "{{ sonarr_namespace }}"
    chart_version: "{{ sonarr_chart_version }}"
    create_namespace: true
    update_repo_cache: true
    values: "{{ lookup('template', 'values.yml.j2') | from_yaml }}"
    wait: true
    state: present
  when: sonarr_enabled
