---
- name: Verify persistence configuration when enabled
  ansible.builtin.assert:
    that:
      - >-
        not sonarr_persistence_enabled or
        (sonarr_existing_claim is defined) or
        (sonarr_storage_class is defined and sonarr_storage_size is defined)
      - >-
        not sonarr_persistence_enabled or
        not (sonarr_existing_claim is defined and sonarr_storage_class is defined)
    fail_msg: >-
      When persistence is enabled, either:
      - Define an existing claim using sonarr_existing_claim
      - OR define both sonarr_storage_class and sonarr_storage_size
      But not both options simultaneously.

- name: Verify storage size format when defined
  ansible.builtin.assert:
    that:
      - >-
        not sonarr_persistence_enabled or
        sonarr_existing_claim is defined or
        sonarr_storage_size | regex_search('^[0-9]+[MGT]i$')
    fail_msg: "Invalid storage size format. Must be in format: 1Gi, 100Mi, 2Ti, etc."
